// Generated from the "Lists" sheet of the meal-plan spreadsheet.
// One-time seed data for the foods library; see scripts/seed-nutrition.mjs.
export const FOODS_SEED = [
  { name: "Large Whole Egg", category: 'protein', serving_label: "2 eggs", calories: 146, protein: 14, fat: 10, carb: 0 },
  { name: "Medium Whole Egg", category: 'protein', serving_label: "2 eggs", calories: 138, protein: 12, fat: 10, carb: 0 },
  { name: "Egg White (Manually Separated)", category: 'protein', serving_label: "3 egg whites", calories: 36, protein: 9, fat: 0, carb: 0 },
  { name: "Liquid Egg White (Carton)", category: 'protein', serving_label: "150ml", calories: 66, protein: 16.4, fat: 0, carb: 0 },
  { name: "Total 0% Greek Yoghurt", category: 'protein', serving_label: "200g", calories: 112, protein: 20, fat: 0, carb: 8 },
  { name: "Total Full Fat Greek Yoghurt", category: 'protein', serving_label: "200g", calories: 202, protein: 18, fat: 10, carb: 10 },
  { name: "0% Cottage Cheese", category: 'protein', serving_label: "200g", calories: 120, protein: 20, fat: 0, carb: 10 },
  { name: "Full Fat Cottage Cheese", category: 'protein', serving_label: "200g", calories: 220, protein: 18, fat: 12, carb: 10 },
  { name: "Skyr Natural Yoghurt", category: 'protein', serving_label: "200g", calories: 124, protein: 22, fat: 0.4, carb: 8 },
  { name: "Whey Protein", category: 'protein', serving_label: "30g", calories: 117, protein: 24, fat: 1, carb: 3 },
  { name: "Whey Isolate", category: 'protein', serving_label: "30g", calories: 111, protein: 25.5, fat: 0.3, carb: 1.5 },
  { name: "Casein Protein", category: 'protein', serving_label: "30g", calories: 110, protein: 21, fat: 1.5, carb: 3 },
  { name: "Semi Skimmed Milk", category: 'protein', serving_label: "200ml", calories: 98, protein: 7.2, fat: 3.4, carb: 9.6 },
  { name: "Lindahls Kvarg", category: 'protein', serving_label: "150g", calories: 94, protein: 16.5, fat: 0.9, carb: 5.1 },
  { name: "Grenade bar", category: 'protein', serving_label: "1 bar", calories: 221, protein: 23.3, fat: 8.2, carb: 13.6 },
  { name: "M&S - King Prawns", category: 'protein', serving_label: "160g cooked/drained", calories: 127, protein: 29.4, fat: 1, carb: 0.2 },
  { name: "Tuna Chunks - Drained", category: 'protein', serving_label: "1 tin drained", calories: 135, protein: 32.5, fat: 0.6, carb: 0 },
  { name: "Heck Chicken Burger", category: 'protein', serving_label: "1 burger", calories: 125, protein: 21.1, fat: 3.8, carb: 1.6 },
  { name: "Heck Chicken Italia Sausages", category: 'protein', serving_label: "2 sausages", calories: 76, protein: 13, fat: 2.3, carb: 0.9 },
  { name: "Chicken Breast", category: 'protein', serving_label: "150g raw/as sold", calories: 165, protein: 34.5, fat: 3, carb: 0 },
  { name: "Chicken Mince 5%", category: 'protein', serving_label: "150g raw/as sold", calories: 173, protein: 28.5, fat: 6.6, carb: 0 },
  { name: "Ribeye Steak", category: 'protein', serving_label: "150g raw/as sold", calories: 301, protein: 32.4, fat: 19, carb: 0 },
  { name: "Sirloin Steak", category: 'protein', serving_label: "150g raw/as sold", calories: 301, protein: 32.4, fat: 19, carb: 0 },
  { name: "Steak - Fillet", category: 'protein', serving_label: "150g raw/as sold", calories: 225, protein: 33, fat: 10.3, carb: 0 },
  { name: "5% Beef Steak Mince", category: 'protein', serving_label: "150g raw/as sold", calories: 198, protein: 32.8, fat: 7.4, carb: 0 },
  { name: "10% Beef Steak Mince", category: 'protein', serving_label: "150g raw/as sold", calories: 253, protein: 29.5, fat: 15, carb: 0 },
  { name: "Mattessons Turkey Bacon", category: 'protein', serving_label: "2 rashers", calories: 73, protein: 15, fat: 1, carb: 1 },
  { name: "Salmon Fillet", category: 'protein', serving_label: "130g raw/as sold", calories: 272, protein: 32.9, fat: 15.6, carb: 0 },
  { name: "Smoked Salmon", category: 'protein', serving_label: "60g", calories: 110, protein: 13.4, fat: 5.9, carb: 0.9 },
  { name: "Eat Lean - Protein Cheese", category: 'protein', serving_label: "30g", calories: 54, protein: 10.8, fat: 0.9, carb: 0.6 },
  { name: "Feta (Apetina Light)", category: 'protein', serving_label: "30g", calories: 49, protein: 5.4, fat: 3, carb: 0 },
  { name: "Halloumi light", category: 'protein', serving_label: "30g", calories: 70, protein: 7.6, fat: 4.3, carb: 0.2 },
  { name: "Tofu", category: 'protein', serving_label: "150g", calories: 178, protein: 19.5, fat: 10.5, carb: 1.5 },
  { name: "Lentils", category: 'protein', serving_label: "60g dry weight", calories: 212, protein: 15.6, fat: 0.6, carb: 36 },
  { name: "Quinoa/Blackrice/Soybeans", category: 'protein', serving_label: "150g cooked", calories: 160, protein: 6.1, fat: 5.8, carb: 20.9 },
  { name: "Kidney Beans", category: 'protein', serving_label: "150g drained", calories: 194, protein: 12, fat: 1.5, carb: 33 },
  { name: "Linda McCartney Vegetarian Sausages", category: 'protein', serving_label: "2 sausages", calories: 181, protein: 12.3, fat: 10.5, carb: 9.3 },
  { name: "Linda McCartney Shredded Hoisin Duck", category: 'protein', serving_label: "100g", calories: 159, protein: 19, fat: 7, carb: 5 },
  { name: "Quorn Peppered Steak", category: 'protein', serving_label: "1 steak", calories: 113, protein: 12, fat: 5, carb: 5 },
  { name: "Quorn Meatballs", category: 'protein', serving_label: "150g", calories: 166, protein: 18, fat: 4.5, carb: 13.5 },
  { name: "Quorn fillets", category: 'protein', serving_label: "150g", calories: 110, protein: 21, fat: 1.5, carb: 3 },
  { name: "Quorn sausages", category: 'protein', serving_label: "2 sausages", calories: 146, protein: 8.7, fat: 8.7, carb: 8.3 },
  { name: "Unsweetened Almond Milk", category: 'protein', serving_label: "250ml", calories: 29, protein: 1, fat: 2.8, carb: 0 },
  { name: "Cod", category: 'protein', serving_label: "150g raw/as sold", calories: 117, protein: 27, fat: 1, carb: 0 },
  { name: "Lean beef mince 5%", category: 'protein', serving_label: "150g raw/as sold", calories: 198, protein: 32.8, fat: 7.4, carb: 0 },
  { name: "Chicken Thigh Skinless", category: 'protein', serving_label: "150g raw/as sold", calories: 182, protein: 28.5, fat: 7.5, carb: 0 },
  { name: "Turkey Breast", category: 'protein', serving_label: "150g raw/as sold", calories: 158, protein: 36, fat: 1.5, carb: 0 },
  { name: "Turkey Mince 2%", category: 'protein', serving_label: "150g raw/as sold", calories: 165, protein: 34.5, fat: 3, carb: 0 },
  { name: "Turkey Mince 7%", category: 'protein', serving_label: "150g raw/as sold", calories: 220, protein: 31.5, fat: 10.5, carb: 0 },
  { name: "Pork Tenderloin", category: 'protein', serving_label: "150g raw/as sold", calories: 210, protein: 39, fat: 6, carb: 0 },
  { name: "Pork Loin Medallions", category: 'protein', serving_label: "150g raw/as sold", calories: 231, protein: 37.5, fat: 9, carb: 0 },
  { name: "Lean Gammon Steak", category: 'protein', serving_label: "150g raw/as sold", calories: 224, protein: 37.5, fat: 7.5, carb: 1.5 },
  { name: "Back Bacon Medallions", category: 'protein', serving_label: "100g", calories: 127, protein: 24, fat: 3, carb: 1 },
  { name: "Lean Ham", category: 'protein', serving_label: "80g", calories: 92, protein: 16, fat: 2.4, carb: 1.6 },
  { name: "Chicken Slices", category: 'protein', serving_label: "80g", calories: 91, protein: 17.6, fat: 1.6, carb: 1.6 },
  { name: "Turkey Slices", category: 'protein', serving_label: "80g", calories: 84, protein: 17.6, fat: 0.8, carb: 1.6 },
  { name: "Beef Jerky", category: 'protein', serving_label: "30g", calories: 89, protein: 15, fat: 1.2, carb: 4.5 },
  { name: "Venison Steak", category: 'protein', serving_label: "150g raw/as sold", calories: 180, protein: 34.5, fat: 4.7, carb: 0 },
  { name: "Duck Breast Skinless", category: 'protein', serving_label: "150g raw/as sold", calories: 210, protein: 34.5, fat: 8, carb: 0 },
  { name: "Lean Pork Mince 5%", category: 'protein', serving_label: "150g raw/as sold", calories: 210, protein: 31.5, fat: 9.3, carb: 0 },
  { name: "Chicken Liver", category: 'protein', serving_label: "100g raw/as sold", calories: 158, protein: 25, fat: 6, carb: 1 },
  { name: "Beef Liver", category: 'protein', serving_label: "100g raw/as sold", calories: 132, protein: 20, fat: 4, carb: 4 },
  { name: "Haddock", category: 'protein', serving_label: "150g raw/as sold", calories: 122, protein: 27, fat: 1.5, carb: 0 },
  { name: "Pollock", category: 'protein', serving_label: "150g raw/as sold", calories: 128, protein: 28.5, fat: 1.5, carb: 0 },
  { name: "Sea Bass", category: 'protein', serving_label: "130g raw/as sold", calories: 162, protein: 26, fat: 6.5, carb: 0 },
  { name: "Hake", category: 'protein', serving_label: "150g raw/as sold", calories: 134, protein: 30, fat: 1.5, carb: 0 },
  { name: "Tinned Salmon", category: 'protein', serving_label: "100g drained", calories: 146, protein: 23, fat: 6, carb: 0 },
  { name: "Crab Meat", category: 'protein', serving_label: "100g drained", calories: 81, protein: 18, fat: 1, carb: 0 },
  { name: "Mussels", category: 'protein', serving_label: "150g cooked", calories: 166, protein: 25.5, fat: 4.5, carb: 6 },
  { name: "Scallops", category: 'protein', serving_label: "150g raw/as sold", calories: 140, protein: 27, fat: 1.5, carb: 4.5 },
  { name: "Squid", category: 'protein', serving_label: "150g raw/as sold", calories: 128, protein: 24, fat: 1.5, carb: 4.5 },
  { name: "Octopus", category: 'protein', serving_label: "150g cooked", calories: 116, protein: 22.5, fat: 1.5, carb: 3 },
  { name: "Fish Pie Mix", category: 'protein', serving_label: "150g raw/as sold", calories: 160, protein: 30, fat: 4.5, carb: 0 },
  { name: "Fage 2% Greek Yoghurt", category: 'protein', serving_label: "200g", calories: 140, protein: 20, fat: 4, carb: 6 },
  { name: "Arla Protein Yoghurt", category: 'protein', serving_label: "200g", calories: 112, protein: 20, fat: 0, carb: 8 },
  { name: "Protein Pudding", category: 'protein', serving_label: "200g", calories: 164, protein: 20, fat: 4, carb: 12 },
  { name: "Protein Mousse", category: 'protein', serving_label: "200g", calories: 156, protein: 20, fat: 4, carb: 10 },
  { name: "Quark Fat Free", category: 'protein', serving_label: "200g", calories: 128, protein: 24, fat: 0, carb: 8 },
  { name: "Mozzarella Light", category: 'protein', serving_label: "30g", calories: 52, protein: 6.9, fat: 2.4, carb: 0.6 },
  { name: "Babybel Light", category: 'protein', serving_label: "1 Babybel", calories: 42, protein: 5, fat: 2.4, carb: 0 },
  { name: "High Protein Milk", category: 'protein', serving_label: "250ml", calories: 122, protein: 12.5, fat: 2.5, carb: 12.5 },
  { name: "Lactose Free Semi Skimmed Milk", category: 'protein', serving_label: "200ml", calories: 99, protein: 7, fat: 3.6, carb: 9.6 },
  { name: "Soya Milk Unsweetened", category: 'protein', serving_label: "250ml", calories: 75, protein: 8.2, fat: 4.5, carb: 0.5 },
  { name: "Tempeh", category: 'protein', serving_label: "150g", calories: 290, protein: 30, fat: 13.5, carb: 12 },
  { name: "Seitan", category: 'protein', serving_label: "150g", calories: 207, protein: 37.5, fat: 3, carb: 7.5 },
  { name: "Edamame Beans", category: 'protein', serving_label: "100g", calories: 125, protein: 11, fat: 5, carb: 9 },
  { name: "Pea Protein Powder", category: 'protein', serving_label: "30g", calories: 112, protein: 22.5, fat: 1.8, carb: 1.5 },
  { name: "soy", category: 'protein', serving_label: "30g", calories: 110, protein: 26.4, fat: 0.3, carb: 0.3 },
  { name: "Mycoprotein Pieces", category: 'protein', serving_label: "150g", calories: 141, protein: 21, fat: 3, carb: 7.5 },
  { name: "Plant-Based Chicken Pieces", category: 'protein', serving_label: "150g", calories: 216, protein: 33, fat: 6, carb: 7.5 },
  { name: "Fridge Raiders Chicken Bites", category: 'protein', serving_label: "45g", calories: 65, protein: 11.2, fat: 1.8, carb: 0.9 },
  { name: "Cooked Chicken Pieces", category: 'protein', serving_label: "100g cooked", calories: 118, protein: 24, fat: 2, carb: 1 },
  { name: "Rotisserie Chicken Breast", category: 'protein', serving_label: "150g cooked", calories: 249, protein: 42, fat: 9, carb: 0 },
  { name: "Tinned Chicken Breast", category: 'protein', serving_label: "100g drained", calories: 105, protein: 24, fat: 1, carb: 0 },
  { name: "Chicken Skewers", category: 'protein', serving_label: "100g cooked", calories: 144, protein: 24, fat: 4, carb: 3 },
  { name: "High Protein Cheese Sauce", category: 'protein', serving_label: "50g", calories: 55, protein: 6, fat: 2, carb: 3 },
  { name: "Greek Yoghurt Garlic Sauce", category: 'protein', serving_label: "50g", calories: 35, protein: 5, fat: 0, carb: 3 },
  { name: "Greek Yoghurt Mint Sauce", category: 'protein', serving_label: "50g", calories: 35, protein: 5, fat: 0, carb: 3 },
  { name: "Quark Garlic Dip", category: 'protein', serving_label: "50g", calories: 32, protein: 6, fat: 0, carb: 2 },
  { name: "Cottage Cheese Sauce", category: 'protein', serving_label: "100g", calories: 80, protein: 11, fat: 2, carb: 4 },
  { name: "Protein Nacho Cheese Dip", category: 'protein', serving_label: "50g", calories: 60, protein: 6, fat: 3, carb: 2 },
  { name: "Fage 5% fat greek yoghurt", category: 'protein', serving_label: "100g", calories: 95, protein: 10, fat: 5, carb: 3.5 },
  { name: "Protein & Fibre Ceylon Cinnamon", category: 'protein', serving_label: "50g", calories: 191, protein: 21, fat: 5.3, carb: 13 },
  { name: "Waitrose Whole milk", category: 'protein', serving_label: "100ml", calories: 66, protein: 3.5, fat: 3.7, carb: 4.7 },
  { name: "Biotiful Gut Health Kefir Yoghurt Original", category: 'protein', serving_label: "115g", calories: 93.75, protein: 7.5, fat: 2.5, carb: 9.25 },
  { name: "Babybel", category: 'protein', serving_label: "1 Babybel", calories: 59, protein: 4.4, fat: 4.6, carb: 0 },
  { name: "Peanut Butter (WEIGHED)", category: 'fat', serving_label: "15g", calories: 94, protein: 3.8, fat: 7.7, carb: 2.1 },
  { name: "Almond Butter (WEIGHED)", category: 'fat', serving_label: "15g", calories: 98, protein: 3.8, fat: 8.3, carb: 0.9 },
  { name: "Walnuts", category: 'fat', serving_label: "20g", calories: 138, protein: 3, fat: 13, carb: 1.4 },
  { name: "Cashews", category: 'fat', serving_label: "20g", calories: 117, protein: 3.6, fat: 10, carb: 3.6 },
  { name: "Almonds", category: 'fat', serving_label: "20g", calories: 119, protein: 4.2, fat: 10, carb: 1.8 },
  { name: "Pecans", category: 'fat', serving_label: "20g", calories: 140, protein: 2, fat: 14, carb: 1 },
  { name: "Olive Oil", category: 'fat', serving_label: "1tsp", calories: 45, protein: 0, fat: 5, carb: 0 },
  { name: "Coconut Oil", category: 'fat', serving_label: "5g", calories: 45, protein: 0, fat: 5, carb: 0 },
  { name: "Avocado (Half)", category: 'fat', serving_label: "70g", calories: 112, protein: 1.4, fat: 10.5, carb: 1.4 },
  { name: "Butter", category: 'fat', serving_label: "10g", calories: 75, protein: 0, fat: 8.2, carb: 0.1 },
  { name: "Red fat Hummus", category: 'fat', serving_label: "30g", calories: 76, protein: 2.2, fat: 5.6, carb: 3.5 },
  { name: "Beet houmous", category: 'fat', serving_label: "30g", calories: 90, protein: 1.8, fat: 7.2, carb: 3.6 },
  { name: "mixed salad", category: 'fat', serving_label: "80g", calories: 16, protein: 0.5, fat: 0.1, carb: 0.3 },
  { name: "Milk whole", category: 'fat', serving_label: "200ml", calories: 130, protein: 7, fat: 7.4, carb: 9.4 },
  { name: "Houmous", category: 'fat', serving_label: "30g", calories: 62, protein: 2.3, fat: 3.1, carb: 5.2 },
  { name: "Light cheddar cheese (cheese)", category: 'fat', serving_label: "20g", calories: 62, protein: 5.6, fat: 4.4, carb: 0 },
  { name: "Options Hot Chocolate", category: 'fat', serving_label: "11g", calories: 40, protein: 1.2, fat: 1.1, carb: 5.3 },
  { name: "Halo Top Ice Cream", category: 'fat', serving_label: "0.5 tub", calories: 180, protein: 5.5, fat: 5.5, carb: 32 },
  { name: "Halo Top Brownie Ice Cream", category: 'fat', serving_label: "0.5 tub", calories: 180, protein: 6.5, fat: 5, carb: 30.5 },
  { name: "Halo Top Cookie Dough Ice Cream", category: 'fat', serving_label: "0.5 tub", calories: 180, protein: 5.5, fat: 5.5, carb: 32 },
  { name: "Light Mayo", category: 'fat', serving_label: "15g", calories: 36, protein: 0.1, fat: 3.3, carb: 1.4 },
  { name: "85% dark chocolate", category: 'fat', serving_label: "10g", calories: 60, protein: 1.2, fat: 4.8, carb: 2 },
  { name: "Chia seeds", category: 'fat', serving_label: "5g", calories: 24, protein: 1, fat: 2, carb: 1 },
  { name: "Flax seeds", category: 'fat', serving_label: "5g", calories: 27, protein: 1, fat: 2, carb: 0 },
  { name: "tinned tomatoes", category: 'fat', serving_label: "1", calories: 80, protein: 4.8, fat: 0.8, carb: 12 },
  { name: "Mixed veggies", category: 'fat', serving_label: "100g", calories: 70, protein: 4, fat: 0, carb: 10 },
  { name: "Macadamia Nuts", category: 'fat', serving_label: "20g", calories: 144, protein: 1.6, fat: 15.2, carb: 2.8 },
  { name: "Brazil Nuts", category: 'fat', serving_label: "20g", calories: 132, protein: 2.8, fat: 13.4, carb: 2.4 },
  { name: "Hazelnuts", category: 'fat', serving_label: "20g", calories: 126, protein: 3, fat: 12.2, carb: 3.4 },
  { name: "Pistachios", category: 'fat', serving_label: "20g", calories: 112, protein: 3.6, fat: 8.8, carb: 5.6 },
  { name: "Pine Nuts", category: 'fat', serving_label: "10g", calories: 67, protein: 1.4, fat: 6.8, carb: 1.3 },
  { name: "Pumpkin Seeds", category: 'fat', serving_label: "15g", calories: 84, protein: 3.1, fat: 6.9, carb: 1.6 },
  { name: "Sunflower Seeds", category: 'fat', serving_label: "15g", calories: 88, protein: 3.1, fat: 7.3, carb: 3 },
  { name: "Sesame Seeds", category: 'fat', serving_label: "10g", calories: 57, protein: 1.8, fat: 5, carb: 2.3 },
  { name: "Hemp Seeds", category: 'fat', serving_label: "10g", calories: 55, protein: 1.8, fat: 4.9, carb: 0.9 },
  { name: "Tahini", category: 'fat', serving_label: "15g", calories: 89, protein: 2.5, fat: 8.1, carb: 3.1 },
  { name: "Avocado Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Rapeseed Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Sesame Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Flaxseed Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Groundnut Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Ghee", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Lurpak Lighter", category: 'fat', serving_label: "10g", calories: 54, protein: 0.1, fat: 6, carb: 0.1 },
  { name: "Clover Light", category: 'fat', serving_label: "10g", calories: 36, protein: 0.1, fat: 4, carb: 0.1 },
  { name: "Flora Light", category: 'fat', serving_label: "10g", calories: 32, protein: 0.1, fat: 3.6, carb: 0.1 },
  { name: "Extra Light Mayo", category: 'fat', serving_label: "15g", calories: 10, protein: 0, fat: 0.3, carb: 0.4 },
  { name: "Garlic Mayo", category: 'fat', serving_label: "10g", calories: 50, protein: 0, fat: 5, carb: 0.1 },
  { name: "Pesto", category: 'fat', serving_label: "15g", calories: 64, protein: 0.8, fat: 6, carb: 0.8 },
  { name: "Green Pesto", category: 'fat', serving_label: "15g", calories: 64, protein: 0.8, fat: 6, carb: 0.8 },
  { name: "Red Pesto", category: 'fat', serving_label: "15g", calories: 54, protein: 0.2, fat: 4.7, carb: 1 },
  { name: "Guacamole", category: 'fat', serving_label: "50g", calories: 80, protein: 1, fat: 7.5, carb: 4.5 },
  { name: "Olives", category: 'fat', serving_label: "30g", calories: 42, protein: 0.3, fat: 4.5, carb: 1.2 },
  { name: "Black Olives", category: 'fat', serving_label: "30g", calories: 33, protein: 0.3, fat: 3.3, carb: 0.9 },
  { name: "Green Olives", category: 'fat', serving_label: "30g", calories: 42, protein: 0.3, fat: 4.5, carb: 0.9 },
  { name: "Light Salad Dressing", category: 'fat', serving_label: "15g", calories: 18, protein: 0.2, fat: 1.4, carb: 1.2 },
  { name: "Caesar Dressing", category: 'fat', serving_label: "15g", calories: 68, protein: 0.2, fat: 6, carb: 0.8 },
  { name: "Balsamic Glaze", category: 'fat', serving_label: "10g", calories: 17, protein: 0.1, fat: 0.1, carb: 4 },
  { name: "Sour Cream", category: 'fat', serving_label: "20g", calories: 38, protein: 0.4, fat: 3.6, carb: 0.8 },
  { name: "Reduced Fat Sour Cream", category: 'fat', serving_label: "20g", calories: 22, protein: 0.6, fat: 2, carb: 0.8 },
  { name: "Creme Fraiche", category: 'fat', serving_label: "20g", calories: 58, protein: 0.4, fat: 5.6, carb: 0.8 },
  { name: "Reduced Fat Creme Fraiche", category: 'fat', serving_label: "20g", calories: 34, protein: 0.6, fat: 3, carb: 1 },
  { name: "Coconut Milk", category: 'fat', serving_label: "50g", calories: 95, protein: 1, fat: 9, carb: 1.5 },
  { name: "Light Coconut Milk", category: 'fat', serving_label: "50g", calories: 35, protein: 0.5, fat: 3, carb: 1.5 },
  { name: "Coconut Cream", category: 'fat', serving_label: "30g", calories: 99, protein: 0.6, fat: 9.6, carb: 1.8 },
  { name: "90% Dark Chocolate", category: 'fat', serving_label: "20g", calories: 118, protein: 1.6, fat: 9.2, carb: 2.8 },
  { name: "Cacao Nibs", category: 'fat', serving_label: "10g", calories: 60, protein: 1.3, fat: 5, carb: 2.4 },
  { name: "Pumpkin Seed Butter", category: 'fat', serving_label: "15g", calories: 86, protein: 2.7, fat: 6.8, carb: 3 },
  { name: "Sunflower Seed Butter", category: 'fat', serving_label: "15g", calories: 84, protein: 3, fat: 6.4, carb: 3 },
  { name: "Light Hummus", category: 'fat', serving_label: "30g", calories: 48, protein: 1.2, fat: 3.3, carb: 4.2 },
  { name: "Reduced Fat Coleslaw", category: 'fat', serving_label: "50g", calories: 75, protein: 2, fat: 5, carb: 4.5 },
  { name: "Aioli", category: 'fat', serving_label: "10g", calories: 65, protein: 0.1, fat: 6.5, carb: 0.1 },
  { name: "Truffle Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Chilli Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Garlic Oil", category: 'fat', serving_label: "5g", calories: 44, protein: 0, fat: 5, carb: 0 },
  { name: "Mozzarella Light (cheese)", category: 'fat', serving_label: "30g", calories: 50, protein: 6.9, fat: 2.4, carb: 0.6 },
  { name: "Mozzarella Full Fat (cheese)", category: 'fat', serving_label: "30g", calories: 84, protein: 5.4, fat: 6.3, carb: 0.6 },
  { name: "Feta Light (cheese)", category: 'fat', serving_label: "30g", calories: 48, protein: 4.5, fat: 2.7, carb: 0.6 },
  { name: "Feta Full Fat (cheese)", category: 'fat', serving_label: "30g", calories: 80, protein: 4.2, fat: 6.3, carb: 1.2 },
  { name: "Halloumi Light (cheese)", category: 'fat', serving_label: "30g", calories: 75, protein: 6.6, fat: 5.1, carb: 0.6 },
  { name: "Halloumi Full Fat (cheese)", category: 'fat', serving_label: "30g", calories: 96, protein: 6.6, fat: 7.5, carb: 0.6 },
  { name: "Goats Cheese (cheese)", category: 'fat', serving_label: "30g", calories: 87, protein: 5.4, fat: 6.6, carb: 0.3 },
  { name: "Brie (cheese)", category: 'fat', serving_label: "30g", calories: 100, protein: 6.2, fat: 8.4, carb: 0.1 },
  { name: "Camembert (cheese)", category: 'fat', serving_label: "30g", calories: 90, protein: 6, fat: 7.2, carb: 0.2 },
  { name: "Cream Cheese Light (cheese)", category: 'fat', serving_label: "30g", calories: 45, protein: 2.1, fat: 3, carb: 1.2 },
  { name: "Cream Cheese Full Fat (cheese)", category: 'fat', serving_label: "30g", calories: 103, protein: 1.8, fat: 10.2, carb: 1 },
  { name: "Ricotta (cheese)", category: 'fat', serving_label: "50g", calories: 87, protein: 5.7, fat: 6.5, carb: 1.5 },
  { name: "Cottage Cheese Full Fat (cheese)", category: 'fat', serving_label: "100g", calories: 110, protein: 11, fat: 4.3, carb: 3 },
  { name: "Parmesan (cheese)", category: 'fat', serving_label: "10g", calories: 40, protein: 3.6, fat: 2.9, carb: 0 },
  { name: "Edam (cheese)", category: 'fat', serving_label: "30g", calories: 107, protein: 7.5, fat: 8.1, carb: 0 },
  { name: "Gouda (cheese)", category: 'fat', serving_label: "30g", calories: 107, protein: 7.5, fat: 8.1, carb: 0.7 },
  { name: "Red Leicester (cheese)", category: 'fat', serving_label: "30g", calories: 125, protein: 7.5, fat: 10.2, carb: 0 },
  { name: "Babybel Light (cheese)", category: 'fat', serving_label: "1 Babybel", calories: 42, protein: 5, fat: 2.4, carb: 0 },
  { name: "Babybel Original (cheese)", category: 'fat', serving_label: "1 Babybel", calories: 61, protein: 4.6, fat: 4.8, carb: 0 },
  { name: "Laughing Cow Light (cheese)", category: 'fat', serving_label: "1 Triangle", calories: 25, protein: 2.1, fat: 1.3, carb: 1 },
  { name: "Blue Cheese (cheese)", category: 'fat', serving_label: "30g", calories: 105, protein: 6.5, fat: 8.7, carb: 0.5 },
  { name: "Stilton (cheese)", category: 'fat', serving_label: "30g", calories: 117, protein: 7, fat: 9.8, carb: 0.2 },
  { name: "Mascarpone (cheese)", category: 'fat', serving_label: "30g", calories: 129, protein: 1.3, fat: 13.2, carb: 1.2 },
  { name: "Paneer (cheese)", category: 'fat', serving_label: "50g", calories: 130, protein: 9, fat: 10, carb: 1 },
  { name: "Burrata (cheese)", category: 'fat', serving_label: "50g", calories: 128, protein: 7, fat: 10, carb: 1 },
  { name: "Grated Mozzarella (cheese)", category: 'fat', serving_label: "30g", calories: 84, protein: 7.2, fat: 6, carb: 0.6 },
  { name: "Reduced Fat Mozzarella (cheese)", category: 'fat', serving_label: "30g", calories: 57, protein: 7.5, fat: 3, carb: 0.8 },
  { name: "Philadelphia Lightest (cheese)", category: 'fat', serving_label: "30g", calories: 30, protein: 3.3, fat: 0.9, carb: 1.5 },
  { name: "Cheese Spread Light (cheese)", category: 'fat', serving_label: "30g", calories: 50, protein: 2.4, fat: 3.5, carb: 1.5 },
  { name: "Laughing Cow Original (cheese)", category: 'fat', serving_label: "1 Triangle", calories: 38, protein: 2, fat: 3, carb: 1 },
  { name: "Goats Cheese Light (cheese)", category: 'fat', serving_label: "30g", calories: 62, protein: 5.4, fat: 4.2, carb: 0.6 },
  { name: "Cottage Cheese Light (cheese)", category: 'fat', serving_label: "100g", calories: 80, protein: 11, fat: 2, carb: 3 },
  { name: "Manchego (cheese)", category: 'fat', serving_label: "30g", calories: 120, protein: 7.5, fat: 9.8, carb: 0.3 },
  { name: "Gruyere (cheese)", category: 'fat', serving_label: "30g", calories: 124, protein: 8.9, fat: 9.6, carb: 0.1 },
  { name: "Emmental (cheese)", category: 'fat', serving_label: "30g", calories: 114, protein: 8.4, fat: 8.4, carb: 0.2 },
  { name: "Wensleydale (cheese)", category: 'fat', serving_label: "30g", calories: 116, protein: 7, fat: 9.6, carb: 0.2 },
  { name: "Double Gloucester (cheese)", category: 'fat', serving_label: "30g", calories: 124, protein: 7.5, fat: 10.2, carb: 0 },
  { name: "Cheese String (cheese)", category: 'fat', serving_label: "1 stick", calories: 61, protein: 4.6, fat: 4.4, carb: 0.5 },
  { name: "Mini Mozzarella Balls (cheese)", category: 'fat', serving_label: "50g", calories: 125, protein: 9, fat: 9, carb: 1 },
  { name: "Full Fat Mayo", category: 'fat', serving_label: "15g", calories: 100, protein: 0.1, fat: 11, carb: 0.2 },
  { name: "Reduced Fat Mayo", category: 'fat', serving_label: "15g", calories: 45, protein: 0.1, fat: 4.5, carb: 1 },
  { name: "Cheese Sauce", category: 'fat', serving_label: "50g", calories: 85, protein: 3, fat: 6, carb: 4.5 },
  { name: "White Sauce", category: 'fat', serving_label: "50g", calories: 70, protein: 2, fat: 4.5, carb: 5 },
  { name: "Carbonara Sauce", category: 'fat', serving_label: "50g", calories: 95, protein: 3, fat: 7, carb: 4 },
  { name: "Creamy Garlic Sauce", category: 'fat', serving_label: "30g", calories: 75, protein: 0.5, fat: 7, carb: 2 },
  { name: "Burger Sauce", category: 'fat', serving_label: "15g", calories: 45, protein: 0.2, fat: 4, carb: 2 },
  { name: "Peri Peri Mayo", category: 'fat', serving_label: "15g", calories: 55, protein: 0.1, fat: 5.5, carb: 1 },
  { name: "Chipotle Mayo", category: 'fat', serving_label: "15g", calories: 60, protein: 0.2, fat: 6, carb: 1 },
  { name: "Ranch Dressing", category: 'fat', serving_label: "15g", calories: 55, protein: 0.2, fat: 5.5, carb: 1 },
  { name: "Blue Cheese Dressing", category: 'fat', serving_label: "15g", calories: 60, protein: 0.5, fat: 6, carb: 1 },
  { name: "Thousand Island Dressing", category: 'fat', serving_label: "15g", calories: 50, protein: 0.2, fat: 4.5, carb: 2 },
  { name: "Tartar Sauce", category: 'fat', serving_label: "15g", calories: 50, protein: 0.2, fat: 5, carb: 1 },
  { name: "Satay Sauce", category: 'fat', serving_label: "30g", calories: 85, protein: 3, fat: 6, carb: 4 },
  { name: "Peanut Sauce", category: 'fat', serving_label: "30g", calories: 90, protein: 3, fat: 7, carb: 4 },
  { name: "Katsu Sauce", category: 'fat', serving_label: "50g", calories: 75, protein: 1, fat: 4, carb: 9 },
  { name: "Curry Paste", category: 'fat', serving_label: "15g", calories: 35, protein: 1, fat: 2, carb: 3 },
  { name: "black bean sauce", category: 'fat', serving_label: "100g", calories: 124, protein: 2.1, fat: 2.2, carb: 23.6 },
  { name: "double cream", category: 'fat', serving_label: "100ml", calories: 467, protein: 1.5, fat: 50.5, carb: 1.6 },
  { name: "tesco chow mein sauce", category: 'fat', serving_label: "100g", calories: 59, protein: 1.2, fat: 1.6, carb: 9.6 },
  { name: "Rice (Dry Weight)", category: 'carb', serving_label: "75g dry", calories: 262, protein: 6, fat: 0.8, carb: 57.8 },
  { name: "Microwave Rice (250g Pouch)", category: 'carb', serving_label: "1 pouch", calories: 376, protein: 8, fat: 4, carb: 77 },
  { name: "White Potato", category: 'carb', serving_label: "250g raw/as sold", calories: 200, protein: 5, fat: 0, carb: 45 },
  { name: "Sweet Potato", category: 'carb', serving_label: "250g raw/as sold", calories: 240, protein: 5, fat: 0, carb: 55 },
  { name: "Sweet Potato Wraps", category: 'carb', serving_label: "1 wrap", calories: 89, protein: 2, fat: 1, carb: 18 },
  { name: "Tortilla Wraps", category: 'carb', serving_label: "1 wrap", calories: 175, protein: 5, fat: 3, carb: 32 },
  { name: "Oats", category: 'carb', serving_label: "50g dry", calories: 174, protein: 5, fat: 3.5, carb: 30.5 },
  { name: "Nairns GF Oatcakes", category: 'carb', serving_label: "2 oatcakes", calories: 84, protein: 2, fat: 4, carb: 10 },
  { name: "Quinoa", category: 'carb', serving_label: "60g dry", calories: 224, protein: 7.8, fat: 3, carb: 41.4 },
  { name: "Bagel Waitrose", category: 'carb', serving_label: "1 bagel", calories: 244, protein: 9.3, fat: 3.8, carb: 43.2 },
  { name: "Genius GF Bread", category: 'carb', serving_label: "2 slices", calories: 180, protein: 2, fat: 4, carb: 34 },
  { name: "Warburton's - Crumpets", category: 'carb', serving_label: "1 crumpet", calories: 94, protein: 3.3, fat: 0.4, carb: 19.4 },
  { name: "Warburton's - Plain Bagel", category: 'carb', serving_label: "1 bagel", calories: 203, protein: 8.5, fat: 1.4, carb: 39.2 },
  { name: "Warburton's - Sliced White Roll", category: 'carb', serving_label: "1 roll", calories: 144, protein: 5.3, fat: 2.3, carb: 25.6 },
  { name: "Raisins", category: 'carb', serving_label: "14g box", calories: 43, protein: 0.5, fat: 0.1, carb: 10 },
  { name: "Kallo Caramel Rice Cakes", category: 'carb', serving_label: "1 rice cake", calories: 40, protein: 1, fat: 0, carb: 9 },
  { name: "Granola", category: 'carb', serving_label: "40g", calories: 168, protein: 4, fat: 5.2, carb: 26.4 },
  { name: "Rice Krispies / Coco Pops", category: 'carb', serving_label: "40g", calories: 152, protein: 2.4, fat: 0.4, carb: 34.8 },
  { name: "Strawberries / Raspberries", category: 'carb', serving_label: "100g", calories: 26, protein: 0.7, fat: 0.3, carb: 5 },
  { name: "Blueberries", category: 'carb', serving_label: "100g", calories: 62, protein: 0.7, fat: 0.3, carb: 14 },
  { name: "Apple", category: 'carb', serving_label: "1 medium", calories: 65, protein: 0.5, fat: 0.3, carb: 15 },
  { name: "Banana", category: 'carb', serving_label: "1 medium", calories: 117, protein: 1.3, fat: 0.4, carb: 27 },
  { name: "Raging Full", category: 'carb', serving_label: "1 scoop", calories: 100, protein: 0, fat: 0, carb: 25 },
  { name: "Ryvita", category: 'carb', serving_label: "2 crispbreads", calories: 64, protein: 1.8, fat: 0.4, carb: 13.4 },
  { name: "Kallo Lightly Salted Rice Cakes", category: 'carb', serving_label: "2 rice cakes", calories: 56, protein: 2, fat: 0, carb: 12 },
  { name: "Fibre One Bar", category: 'carb', serving_label: "1 bar", calories: 77, protein: 1.2, fat: 3, carb: 11.3 },
  { name: "Soreen Original Loaf", category: 'carb', serving_label: "50g", calories: 155, protein: 3.7, fat: 0.9, carb: 33 },
  { name: "Snack a Jacks - Salt Vinegar", category: 'carb', serving_label: "23g bag", calories: 93, protein: 1.6, fat: 1.7, carb: 17.8 },
  { name: "Weetabix", category: 'carb', serving_label: "2 biscuits", calories: 122, protein: 3.5, fat: 1.4, carb: 23.8 },
  { name: "Yorkshire Pudding", category: 'carb', serving_label: "1 pudding", calories: 111, protein: 3.8, fat: 4.4, carb: 14 },
  { name: "Broccoli", category: 'carb', serving_label: "100g", calories: 31, protein: 2.8, fat: 0.4, carb: 4 },
  { name: "Honey", category: 'carb', serving_label: "10g", calories: 33, protein: 0, fat: 0, carb: 8.2 },
  { name: "Jasons Sourdough", category: 'carb', serving_label: "1 slice", calories: 119, protein: 5.4, fat: 0.4, carb: 23.4 },
  { name: "Spinach", category: 'carb', serving_label: "50g", calories: 10, protein: 1.4, fat: 0.2, carb: 0.7 },
  { name: "Spaghetti Pasta (RAW)", category: 'carb', serving_label: "75g dry", calories: 262, protein: 9, fat: 1.1, carb: 54 },
  { name: "Bagel Thin", category: 'carb', serving_label: "1 bagel thin", calories: 123, protein: 4.9, fat: 0.7, carb: 24.2 },
  { name: "Frozen Mixed Vegetables", category: 'carb', serving_label: "100g", calories: 48, protein: 2.8, fat: 0.5, carb: 8 },
  { name: "White Pasta (RAW)", category: 'carb', serving_label: "75g dry", calories: 262, protein: 9, fat: 1.1, carb: 54 },
  { name: "Wholewheat Pasta (RAW)", category: 'carb', serving_label: "75g dry", calories: 248, protein: 10, fat: 1.8, carb: 48 },
  { name: "Basmati Rice (Cooked)", category: 'carb', serving_label: "180g cooked", calories: 224, protein: 4.9, fat: 0.5, carb: 50 },
  { name: "Jasmine Rice (Cooked)", category: 'carb', serving_label: "180g cooked", calories: 222, protein: 4.5, fat: 0.5, carb: 50 },
  { name: "Egg Noodles (Cooked)", category: 'carb', serving_label: "180g cooked", calories: 248, protein: 9, fat: 3.6, carb: 45 },
  { name: "Rice Noodles (Cooked)", category: 'carb', serving_label: "180g cooked", calories: 198, protein: 3.6, fat: 0.4, carb: 45 },
  { name: "Couscous (Dry Weight)", category: 'carb', serving_label: "60g dry", calories: 210, protein: 7.5, fat: 0.9, carb: 43 },
  { name: "New Potatoes", category: 'carb', serving_label: "250g raw/as sold", calories: 191, protein: 5, fat: 0.3, carb: 42 },
  { name: "Jacket Potato", category: 'carb', serving_label: "300g raw/as sold", calories: 243, protein: 6, fat: 0.3, carb: 54 },
  { name: "Butternut Squash", category: 'carb', serving_label: "200g raw/as sold", calories: 106, protein: 2, fat: 0.2, carb: 24 },
  { name: "Sourdough Bread", category: 'carb', serving_label: "2 slices", calories: 233, protein: 10, fat: 1, carb: 46 },
  { name: "Wholemeal Bread", category: 'carb', serving_label: "2 slices", calories: 178, protein: 8, fat: 2, carb: 32 },
  { name: "White Bread", category: 'carb', serving_label: "2 slices", calories: 186, protein: 6, fat: 2, carb: 36 },
  { name: "Pitta Bread", category: 'carb', serving_label: "1 pitta", calories: 173, protein: 6, fat: 1, carb: 35 },
  { name: "Naan Bread", category: 'carb', serving_label: "0.5 naan", calories: 187, protein: 5, fat: 3, carb: 35 },
  { name: "English Muffin", category: 'carb', serving_label: "1 muffin", calories: 142, protein: 5, fat: 1.5, carb: 27 },
  { name: "Wrap Thin", category: 'carb', serving_label: "1 wrap", calories: 134, protein: 4, fat: 2, carb: 25 },
  { name: "Cornflakes", category: 'carb', serving_label: "40g", calories: 152, protein: 3, fat: 0.4, carb: 34 },
  { name: "Bran Flakes", category: 'carb', serving_label: "40g", calories: 133, protein: 4, fat: 1, carb: 27 },
  { name: "Shreddies", category: 'carb', serving_label: "40g", calories: 145, protein: 4, fat: 1, carb: 30 },
  { name: "Cream Of Rice", category: 'carb', serving_label: "50g dry", calories: 180, protein: 4, fat: 0.5, carb: 40 },
  { name: "Bagel Thins", category: 'carb', serving_label: "1 thin", calories: 123, protein: 4.9, fat: 0.7, carb: 24.2 },
  { name: "Rice Cakes Plain", category: 'carb', serving_label: "2 cakes", calories: 63, protein: 1.4, fat: 0.2, carb: 14 },
  { name: "Dates", category: 'carb', serving_label: "30g", calories: 88, protein: 0.7, fat: 0.1, carb: 21 },
  { name: "Mango", category: 'carb', serving_label: "150g", calories: 100, protein: 1.2, fat: 0.6, carb: 22.5 },
  { name: "Pineapple", category: 'carb', serving_label: "150g", calories: 77, protein: 0.8, fat: 0.2, carb: 18 },
  { name: "Orange", category: 'carb', serving_label: "1 medium", calories: 67, protein: 1.2, fat: 0.2, carb: 15 },
  { name: "Grapes", category: 'carb', serving_label: "100g", calories: 72, protein: 0.6, fat: 0.2, carb: 17 },
  { name: "Kiwi", category: 'carb', serving_label: "2 kiwis", calories: 94, protein: 1.6, fat: 0.8, carb: 20 },
  { name: "Baked Beans", category: 'carb', serving_label: "150g", calories: 155, protein: 7.5, fat: 0.6, carb: 30 },
  { name: "Chickpeas", category: 'carb', serving_label: "150g drained", calories: 220, protein: 12, fat: 4.5, carb: 33 },
  { name: "Black Beans", category: 'carb', serving_label: "150g drained", calories: 198, protein: 12, fat: 1.5, carb: 34 },
  { name: "Sweetcorn", category: 'carb', serving_label: "100g drained", calories: 99, protein: 3.3, fat: 1.5, carb: 18 },
  { name: "Peas", category: 'carb', serving_label: "100g", calories: 64, protein: 5, fat: 0.5, carb: 10 },
  { name: "Jam", category: 'carb', serving_label: "15g", calories: 40, protein: 0, fat: 0, carb: 10 },
  { name: "Maple Syrup", category: 'carb', serving_label: "15g", calories: 40, protein: 0, fat: 0, carb: 10 },
  { name: "Tomato Pasta Sauce", category: 'carb', serving_label: "50g", calories: 35, protein: 1, fat: 0.5, carb: 6.5 },
  { name: "Passata", category: 'carb', serving_label: "100g", calories: 32, protein: 1.5, fat: 0.2, carb: 6 },
  { name: "Ketchup", category: 'carb', serving_label: "15g", calories: 16, protein: 0.2, fat: 0, carb: 3.8 },
  { name: "BBQ Sauce", category: 'carb', serving_label: "15g", calories: 26, protein: 0.2, fat: 0, carb: 6.3 },
  { name: "Sweet Chilli Sauce", category: 'carb', serving_label: "15g", calories: 35, protein: 0, fat: 0, carb: 8.8 },
  { name: "Teriyaki Sauce", category: 'carb', serving_label: "15g", calories: 27, protein: 0.5, fat: 0, carb: 6 },
  { name: "Hoisin Sauce", category: 'carb', serving_label: "15g", calories: 34, protein: 0.3, fat: 0.3, carb: 7 },
  { name: "Curry Sauce", category: 'carb', serving_label: "50g", calories: 50, protein: 1, fat: 1.5, carb: 8 },
  { name: "Gravy", category: 'carb', serving_label: "50g", calories: 20, protein: 0.5, fat: 0.5, carb: 3 },
  { name: "Salsa", category: 'carb', serving_label: "30g", calories: 10, protein: 0.4, fat: 0.1, carb: 2 },
  { name: "Brown Sauce", category: 'carb', serving_label: "15g", calories: 18, protein: 0.2, fat: 0, carb: 4.2 },
  { name: "Mango Chutney", category: 'carb', serving_label: "15g", calories: 40, protein: 0.1, fat: 0, carb: 10 },
  { name: "Cranberry Sauce", category: 'carb', serving_label: "15g", calories: 25, protein: 0, fat: 0, carb: 6 },
  { name: "Apple Sauce", category: 'carb', serving_label: "15g", calories: 20, protein: 0, fat: 0, carb: 5 },
  { name: "tesco blueberry high protein pancake", category: 'carb', serving_label: "1 pancake", calories: 155, protein: 10, fat: 4.2, carb: 18.7 },
  { name: "protein noodles", category: 'carb', serving_label: "100g", calories: 153, protein: 9.4, fat: 1.1, carb: 25.4 },
  { name: "protein bagel thin", category: 'carb', serving_label: "1 bagel thin", calories: 154, protein: 8.1, fat: 2, carb: 24.4 },
  { name: "protein bagel", category: 'carb', serving_label: "1 bagel", calories: 251, protein: 12, fat: 2.6, carb: 31 },
  { name: "gym kitchen pancake", category: 'carb', serving_label: "1 pancake", calories: 109, protein: 6.2, fat: 2.3, carb: 15.5 },
];
